version: "3.9"
services:
  client-react-vite-dev:
    image: maroinekhallou/react-app:dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    networks:
      - frontend
    ports:
      - 8080:8080
networks:
  frontend:
