version: '3.7'
services:
  react-app-prod:
    image: maroinekhallou/react-app:prod
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
networks:
  frontend:
