name: Deploy to PROD
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Sync dev to prod
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b prod
          git reset --hard dev
          git push --force origin prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push_to_registry:
    needs: sync_prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./dockerfile_prod
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:prod

  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect to EC2 and run commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_PROD_HOST }} << 'EOF'
            git clone --branch prod https://github.com/maroine-soprano/react-docker-github-actions
            cd react-docker-github-actions
            docker stack deploy -c docker-swarm.yml react-app
            cd ..
            rm -rf react-docker-github-actions
          EOF
