name: Push Image to Docker Hub
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repository"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose_dev
          push: true
          tags: maroinekhallou/react-app:dev
