name: Push Image to Docker Hub
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $password | docker login -u $username --password-stdin

      - name: Build the Docker image
        run: docker build -f ./dockerfile_dev -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:dev

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-image-test:latest
